- name: Install Redis Repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis Module
  ansible.builtin.shell: yum module enable redis:redmi-6.2 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: update Listen Address /etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: update Listen Address /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes