- name: configure yum repo for mysql
  ansible.builtin.copy:
  src: mysql.repo
  dest: /etc/yum.repos.d/mysql.repo

- name: Disable default Mysql version
  ansible.builtin.shell: yum module disable mysql -y

- name: Install Mysql Community server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: start Mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1